// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // The Prisma CLI (migrate/db push/studio) needs a direct, non-pooled
    // connection — the app's runtime queries use DATABASE_URL (pooled)
    // separately, via the adapter in src/lib/prisma.ts.
    url: process.env["DIRECT_URL"],
  },
});
